### ISSUE TITLE
How to resolve the mobx warning

### ISSUE THREAD

**Issue by FoxChin** [Hancoson/react-mobx-demo#1]
I use `create-react-app` build my project. But when I import `mobx-react` and use  `<provider>`, I get the warning: `[mobx] Warning: there are multiple mobx instances active.This might lead to unexpected results.`
Need your help, thanks.

**Comment by Hancoson** [comment]
@FoxChin： I'm not sure what caused your problem, too. Maybe it's the version of the mobx library.

https://github.com/mobxjs/mobx-angular/issues/37

**Comment by FoxChin** [comment]
@Hancoson Thanks for your answer. I will consider the version of the mobx and the issue you commented to find some clues.
